apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-core
  namespace: securebank
  labels: { app: securebank-core }
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  selector:
    matchLabels: { app: securebank-core }
  template:
    metadata:
      labels: { app: securebank-core }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile: { type: RuntimeDefault }
      terminationGracePeriodSeconds: 40
      containers:
        - name: app
          image: ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/securebank-core:latest   # replaced by Jenkins
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: { name: securebank-config }
            - secretRef: { name: securebank-secrets }
          resources:
            requests: { cpu: "500m", memory: "768Mi" }
            limits: { cpu: "1", memory: "1Gi" }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          volumeMounts:
            - { name: tmp, mountPath: /tmp }
          startupProbe:
            httpGet: { path: /actuator/health/liveness, port: 8080 }
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8080 }
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8080 }
            periodSeconds: 5
          lifecycle:
            preStop:
              exec: { command: ["sh", "-c", "sleep 10"] }
      volumes:
        - name: tmp
          emptyDir: {}
