apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: securebank-core
  namespace: securebank
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: securebank-core
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: securebank-core
  namespace: securebank
spec:
  minAvailable: 2
  selector:
    matchLabels: { app: securebank-core }
