package com.securebank.common;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.securebank.account.Account;
import com.securebank.account.AccountRepository;
import com.securebank.audit.AuditService;
import com.securebank.beneficiary.Beneficiary;
import com.securebank.beneficiary.BeneficiaryDtos.AddBeneficiaryRequest;
import com.securebank.beneficiary.BeneficiaryRepository;
import com.securebank.beneficiary.BeneficiaryService;
import com.securebank.customer.Customer;
import com.securebank.customer.CustomerDtos.CustomerResponse;
import com.securebank.customer.CustomerDtos.KycRequest;
import com.securebank.customer.CustomerRepository;
import com.securebank.customer.CustomerService;
import com.securebank.customer.KycStatus;
import java.time.Instant;
import java.util.Optional;
import org.junit.jupiter.api.Test;

class CustomerAndBeneficiaryServiceTest {

    CustomerRepository customers = mock(CustomerRepository.class);
    AuditService audit = mock(AuditService.class);
    CustomerService customerService = new CustomerService(customers, audit);

    private Customer customer(KycStatus status) {
        Customer c = new Customer();
        c.setKycStatus(status);
        c.setFullName("A");
        when(customers.findById(1L)).thenReturn(Optional.of(c));
        return c;
    }

    @Test
    void kycSubmitStoresDataAndMovesToPending() {
        Customer c = customer(KycStatus.NOT_SUBMITTED);
        CustomerResponse r = customerService.submitKyc(1L, new KycRequest("ABCDE1234F", "123456789012", "addr"));
        assertThat(c.getKycStatus()).isEqualTo(KycStatus.PENDING);
        assertThat(r.panMasked()).isEqualTo("******234F");
        assertThat(r.aadhaarMasked()).endsWith("9012").startsWith("********");
    }

    @Test
    void kycCannotBeResubmittedWhilePendingOrVerified() {
        customer(KycStatus.PENDING);
        assertThatThrownBy(() -> customerService.submitKyc(1L, new KycRequest("ABCDE1234F", "123456789012", "a")))
                .isInstanceOf(BusinessException.class);
        customer(KycStatus.VERIFIED);
        assertThatThrownBy(() -> customerService.submitKyc(1L, new KycRequest("ABCDE1234F", "123456789012", "a")))
                .isInstanceOf(BusinessException.class);
    }

    @Test
    void rejectedKycCanBeResubmitted() {
        Customer c = customer(KycStatus.REJECTED);
        c.setKycRejectionReason("blurry");
        customerService.submitKyc(1L, new KycRequest("ABCDE1234F", "123456789012", "a"));
        assertThat(c.getKycStatus()).isEqualTo(KycStatus.PENDING);
        assertThat(c.getKycRejectionReason()).isNull();
    }

    @Test
    void adminReviewApproveRejectAndGuard() {
        Customer c = customer(KycStatus.PENDING);
        assertThat(customerService.reviewKyc(1L, true, null, 9L).kycStatus()).isEqualTo(KycStatus.VERIFIED);
        assertThatThrownBy(() -> customerService.reviewKyc(1L, true, null, 9L)).isInstanceOf(BusinessException.class);
        c.setKycStatus(KycStatus.PENDING);
        assertThat(customerService.reviewKyc(1L, false, "bad doc", 9L).kycRejectionReason()).isEqualTo("bad doc");
    }

    @Test
    void unlockResetsCounters() {
        Customer c = customer(KycStatus.VERIFIED);
        c.setFailedLoginAttempts(4);
        c.setLockedUntil(Instant.now().plusSeconds(100));
        customerService.unlock(1L, 9L);
        assertThat(c.getFailedLoginAttempts()).isZero();
        assertThat(c.getLockedUntil()).isNull();
        assertThat(customerService.getProfile(1L).id()).isNull(); // id is generated by the DB, not set in this unit test
    }

    // ---------------- beneficiaries ----------------
    BeneficiaryRepository beneficiaries = mock(BeneficiaryRepository.class);
    AccountRepository accounts = mock(AccountRepository.class);
    BeneficiaryService beneficiaryService = new BeneficiaryService(beneficiaries, accounts, audit);

    private Account account(boolean system) {
        Account a = new Account();
        a.setAccountNumber("SB0000000002");
        a.setSystemAccount(system);
        return a;
    }

    @Test
    void addBeneficiaryHappyPath() {
        when(accounts.findByAccountNumber("SB0000000002")).thenReturn(Optional.of(account(false)));
        when(beneficiaries.findByCustomerIdAndAccountNumber(1L, "SB0000000002")).thenReturn(Optional.empty());
        var r = beneficiaryService.add(1L, new AddBeneficiaryRequest("SB0000000002", " Bob ", "bobby"));
        assertThat(r.name()).isEqualTo("Bob");
        verify(beneficiaries).save(any(Beneficiary.class));
    }

    @Test
    void addBeneficiaryRejectsUnknownSystemAndDuplicate() {
        when(accounts.findByAccountNumber("SB0000000002")).thenReturn(Optional.empty());
        assertThatThrownBy(() -> beneficiaryService.add(1L, new AddBeneficiaryRequest("SB0000000002", "Bob", null)))
                .isInstanceOf(BusinessException.class);

        when(accounts.findByAccountNumber("SB0000000002")).thenReturn(Optional.of(account(true)));
        assertThatThrownBy(() -> beneficiaryService.add(1L, new AddBeneficiaryRequest("SB0000000002", "Bob", null)))
                .isInstanceOf(BusinessException.class);

        when(accounts.findByAccountNumber("SB0000000002")).thenReturn(Optional.of(account(false)));
        Beneficiary existing = new Beneficiary();
        org.springframework.test.util.ReflectionTestUtils.setField(existing, "id", 5L);
        when(beneficiaries.findByCustomerIdAndAccountNumber(1L, "SB0000000002")).thenReturn(Optional.of(existing));
        assertThatThrownBy(() -> beneficiaryService.add(1L, new AddBeneficiaryRequest("SB0000000002", "Bob", null)))
                .isInstanceOfSatisfying(BusinessException.class, e -> assertThat(e.getCode()).isEqualTo(ErrorCode.DUPLICATE));
    }

    @Test
    void removedBeneficiaryIsSoftDeletedAndCanBeReAdded() {
        Beneficiary b = new Beneficiary();
        org.springframework.test.util.ReflectionTestUtils.setField(b, "id", 5L);
        b.setAccountNumber("SB0000000002");
        when(beneficiaries.findByIdAndCustomerId(5L, 1L)).thenReturn(Optional.of(b));
        beneficiaryService.remove(1L, 5L);
        assertThat(b.isActive()).isFalse();

        assertThatThrownBy(() -> beneficiaryService.remove(1L, 5L)).isInstanceOf(BusinessException.class);

        when(accounts.findByAccountNumber("SB0000000002")).thenReturn(Optional.of(account(false)));
        when(beneficiaries.findByCustomerIdAndAccountNumber(1L, "SB0000000002")).thenReturn(Optional.of(b));
        beneficiaryService.add(1L, new AddBeneficiaryRequest("SB0000000002", "Bob", null));
        assertThat(b.isActive()).isTrue();
    }

    @Test
    void listMapsActiveBeneficiaries() {
        Beneficiary b = new Beneficiary();
        b.setAccountNumber("SB0000000002");
        b.setName("Bob");
        when(beneficiaries.findByCustomerIdAndActiveTrueOrderByIdAsc(1L)).thenReturn(java.util.List.of(b));
        assertThat(beneficiaryService.list(1L)).hasSize(1);
    }

    @Test
    void maskingAndClientContext() {
        assertThat(Masking.mask(null, 4)).isNull();
        assertThat(Masking.mask("abc", 4)).isEqualTo("***");
        assertThat(Masking.mask("1234567890", 4)).isEqualTo("******7890");

        var req = new org.springframework.mock.web.MockHttpServletRequest();
        req.setRemoteAddr("10.0.0.5");
        assertThat(ClientContext.from(req, " in ").country()).isEqualTo("IN");
        assertThat(ClientContext.from(req, null).ip()).isEqualTo("10.0.0.5");
        req.addHeader("X-Forwarded-For", "8.8.8.8, 10.0.0.1");
        assertThat(ClientContext.from(req, "").ip()).isEqualTo("8.8.8.8");
        assertThat(ClientContext.from(req, "").country()).isNull();
    }
}
